# Generated by Django 3.1.3 on 2020-12-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
